# Конфигурация SNMP агента
agentAddress udp:161

sysLocation "Data Center, Rack 01"
sysContact  "Иванов Иван <ivanov@university.ru>"
sysName     "snmp-server"

rocommunity public default

disk / 10000
load 12 14 14

extend    echo_test   /bin/echo "Hello from SNMP extend"
extend    pg_pow      /usr/bin/psql -U postgres -tA -c "SELECT pow(2, 10);"
extend    pg_connections /usr/bin/psql -U postgres -tA -c "SELECT COUNT(*) FROM pg_stat_activity;"
